version: 2
updates:
- package-ecosystem: docker
  directory: "/docker/py"
  schedule:
    interval: daily
  open-pull-requests-limit: 5
- package-ecosystem: "pip"
  directory: "/docker/py"
  schedule:
    interval: daily
  open-pull-requests-limit: 5
- package-ecosystem: "pip"
  directory: "/renku-requirements"
  schedule:
    interval: daily
  open-pull-requests-limit: 5
- package-ecosystem: docker
  directory: "/docker/r"
  schedule:
    interval: daily
  open-pull-requests-limit: 5
