version: 2
updates:
- package-ecosystem: docker
  directory: "/docker/py"
  schedule:
    interval: daily
  open-pull-requests-limit: 5
- package-ecosystem: docker
  directory: "/docker/r"
  schedule:
    interval: daily
  open-pull-requests-limit: 5
- package-ecosystem: docker
  directory: "/docker/cuda"
  schedule:
    interval: daily
  open-pull-requests-limit: 5
- package-ecosystem: docker
  directory: "/docker/cuda-tf"
  schedule:
    interval: daily
  open-pull-requests-limit: 5
- package-ecosystem: docker
  directory: "/docker/generic"
  schedule:
    interval: daily
  open-pull-requests-limit: 5
- package-ecosystem: docker
  directory: "/docker/vnc"
  schedule:
    interval: daily
  open-pull-requests-limit: 5
- package-ecosystem: docker
  directory: "/docker/qgis"
  schedule:
    interval: daily
  open-pull-requests-limit: 5

#
# python dependencies
#

- package-ecosystem: "pip"
  directory: "/docker/py"
  schedule:
    interval: daily
  open-pull-requests-limit: 5
- package-ecosystem: "pip"
  directory: "/docker/py/renku-requirements"
  schedule:
    interval: daily
  open-pull-requests-limit: 5
