version: 2
updates:
- package-ecosystem: docker
  directory: "/docker/py"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
- package-ecosystem: "pip"
  directory: "/docker/py/requirements.txt"
  schedule:
    interval: daily
  open-pull-request-limit: 10
- package-ecosystem: docker
  directory: "/docker/r"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
