name: Renku Docker Image CI

on: 
  #  pull_request:
  #    branches: [master]
  #    paths-ignore: ['Makefile', 'docker/**']
  push:
      branches: ['*']
      paths: ['Makefile', 'docker/**']

env:
  DOCKER_NAME: "renku/renkulab"

jobs:

  lint:
    strategy:
      fail-fast: true
      matrix:
        DOCKERFILE_PATH:
        - docker/py/Dockerfile
        - docker/r/Dockerfile
        - docker/cuda/Dockerfile
        - docker/cuda-tf/Dockerfile
        - docker/generic/Dockerfile
        - docker/vnc/Dockerfile
        - docker/matlab/Dockerfile
        - docker/julia/Dockerfile
        - docker/batch/Dockerfile
        - docker/qgis/Dockerfile
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: hadolint/hadolint-action@v2.0.0
      with:
        dockerfile: ${{ matrix.DOCKERFILE_PATH }}
        config: .hadolint.yaml

  build-py:
    needs: lint
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        BASE_IMAGE_TAG:
          - lab-3.4.0
          - python-3.10.6
          - python-3.9.12
          - python-3.8.13

    steps:
    - name: Docker Login
      uses: Azure/docker-login@v1
      with:
        username: ${{ secrets.RENKU_DOCKER_USERNAME }}
        password: ${{ secrets.RENKU_DOCKER_PASSWORD }}

    - uses: actions/checkout@v3
    - name: Build renku project python-based docker images
      id: build-image
      run: |
        if [[ ${{ github.ref }} == refs/tags* ]]; then
          export LABEL=$(echo ${{ github.ref }} | cut -d / -f 3)
        else
          export LABEL=$(echo ${{ github.sha }} | cut -c 1-7)
        fi

        # This ensures the same image tags as before are built, in addition to new ones
        if [[ "${{ matrix.BASE_IMAGE_TAG }}" == lab-* ]]; then
          export LABEL_PREFIX=3.9
        else
          export LABEL_PREFIX=${{ matrix.BASE_IMAGE_TAG }}
        fi

        # needed by the makefile
        export DOCKER_PREFIX="renku/renkulab"    
        export DOCKER_LABEL="${LABEL_PREFIX}-${LABEL}"
        # this is required by the makefile
        export GIT_MASTER_HEAD_SHA=$(git rev-parse --short=7 --verify HEAD)
        make py 
        # docker build docker/py --tag $DOCKER_NAME-py:$LABEL_PREFIX-$LABEL --build-arg BASE_IMAGE="jupyter/base-notebook:${{ matrix.BASE_IMAGE_TAG }}"
        echo "IMAGE_NAME=${DOCKER_PREFIX}-py:${DOCKER_LABEL}" >> $GITHUB_OUTPUT

    - name: Image Acceptance Tests
      uses: cypress-io/github-action@v4
      env:
        TEST_IMAGE_NAME: ${{ steps.build-image.outputs.IMAGE_NAME }}
        TEST_USER_NAME: jovyan
        TEST_SPEC: jupyterlab.cy.ts
      with:
        working-directory: tests
        command: npx mocha -r ts-node/register index.ts

    - name: Push to docker
      run: |
        docker push ${{ steps.build-image.outputs.IMAGE_NAME }}

        # on master push latest image - the lab-* image is tagged latest
        if [ "$REF" == "refs/heads/master" ] && [ "${{ matrix.BASE_IMAGE_TAG }}" == lab-* ]; then
          docker tag ${{ steps.build-image.outputs.IMAGE_NAME }} $DOCKER_NAME-py:latest
          docker push $DOCKER_NAME-py:latest
        fi

  build-cuda:
    needs: build-py
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        include:
          # taken from tensorflow compatibility chart at https://www.tensorflow.org/install/source#gpu
          - CUDA_VERSION: "11.2"
            PYTHON_VERSION: "3.9.12"
            EXTRA_LIBRARIES: ""
            CUDA_CUDART_PACKAGE: "cuda-cudart-11-2=11.2.152-1"
            CUDA_COMPAT_PACKAGE: "cuda-compat-11-2"
            LIBCUDNN_PACKAGE: "libcudnn8=8.1.1.33-1+cuda11.2"
          - CUDA_VERSION: "11.3"
            PYTHON_VERSION: "3.9.12"
            EXTRA_LIBRARIES: ""
            CUDA_CUDART_PACKAGE: "cuda-cudart-11-3=11.3.109-1"
            CUDA_COMPAT_PACKAGE: "cuda-compat-11-3"
            LIBCUDNN_PACKAGE: "libcudnn8=8.2.1.32-1+cuda11.3"
          - CUDA_VERSION: "11.4"
            PYTHON_VERSION: "3.9.12"
            EXTRA_LIBRARIES: ""
            CUDA_CUDART_PACKAGE: "cuda-cudart-11-4=11.4.148-1"
            CUDA_COMPAT_PACKAGE: "cuda-compat-11-4"
            LIBCUDNN_PACKAGE: "libcudnn8=8.2.4.15-1+cuda11.4"
          - CUDA_VERSION: "11.5"
            PYTHON_VERSION: "3.9.12"
            EXTRA_LIBRARIES: ""
            CUDA_CUDART_PACKAGE: "cuda-cudart-11-5=11.5.117-1"
            CUDA_COMPAT_PACKAGE: "cuda-compat-11-5"
            LIBCUDNN_PACKAGE: "libcudnn8=8.3.2.44-1+cuda11.5"
          - CUDA_VERSION: "11.7"
            PYTHON_VERSION: "3.9.12"
            EXTRA_LIBRARIES: ""
            CUDA_CUDART_PACKAGE: "cuda-cudart-11-7=11.7.60-1"
            CUDA_COMPAT_PACKAGE: "cuda-compat-11-7"
            LIBCUDNN_PACKAGE: "libcudnn8=8.5.0.96-1+cuda11.7"
          # note cuda 11.8 is available now, but there I could not
          # fund a cuda-compat package in the ubuntu repos

    steps:
    - name: Docker Login
      uses: Azure/docker-login@v1
      with:
        username: ${{ secrets.RENKU_DOCKER_USERNAME }}
        password: ${{ secrets.RENKU_DOCKER_PASSWORD }}

    - uses: actions/checkout@v3
    - name: Build renku project python-based docker image extensions
      id: build-image
      run: |
        # cd docker/cuda

        if [[ ${{ github.ref }} == refs/tags* ]]; then
          export LABEL=$(echo ${{ github.ref }} | cut -d / -f 3)
        else
          export LABEL=$(echo ${{ github.sha }} | cut -c 1-7)
        fi

        export DOCKER_PREFIX="renku/renkulab"    
        export DOCKER_LABEL="${{ matrix.CUDA_VERSION }}-${LABEL}"
        export BASE_IMAGE="renku/renkulab-py:python-${{ matrix.PYTHON_VERSION }}-$LABEL" 
        export CUDA_VERSION="${{ matrix.CUDA_VERSION }}" 
        export EXTRA_LIBRARIES="${{ matrix.EXTRA_LIBRARIES }}" 
        export CUDA_CUDART_PACKAGE="${{ matrix.CUDA_CUDART_PACKAGE }}" 
        export CUDA_COMPAT_PACKAGE="${{ matrix.CUDA_COMPAT_PACKAGE }}" 
        export LIBCUDNN_PACKAGE="${{ matrix.LIBCUDNN_PACKAGE }}" 
        make cuda
        echo "IMAGE_NAME=$DOCKER_NAME-cuda:$DOCKER_LABEL" >> $GITHUB_OUTPUT
        
    - name: Image Acceptance Tests
      uses: cypress-io/github-action@v4
      env:
        TEST_IMAGE_NAME: ${{ steps.build-image.outputs.IMAGE_NAME }}
        TEST_USER_NAME: jovyan
        TEST_SPEC: jupyterlab.cy.ts
      with:
        working-directory: tests
        command: npx mocha -r ts-node/register index.ts
    - name: Push to docker
      run: |
        docker push ${{ steps.build-image.outputs.IMAGE_NAME }}

        # on master push latest image
        if [ "$REF" == "refs/heads/master" ] && [ "${{ matrix.CUDA_VERSION }}" == "11.5" ]; then
          docker tag ${{ steps.build-image.outputs.IMAGE_NAME }} $DOCKER_NAME-cuda:latest
          docker push $DOCKER_NAME-cuda:latest
        fi

  build-cuda-tf:
    needs: build-cuda
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        include:
          # taken from tensorflow compatibility chart at https://www.tensorflow.org/install/source#gpu
          - TF_VERSION: "2.7"
            CUDA_VERSION: "11.2"
          - TF_VERSION: "2.9"
            CUDA_VERSION: "11.2"

    steps:
    - name: Docker Login
      uses: Azure/docker-login@v1
      with:
        username: ${{ secrets.RENKU_DOCKER_USERNAME }}
        password: ${{ secrets.RENKU_DOCKER_PASSWORD }}

    - uses: actions/checkout@v3
    - name: Build renku project python-based docker image extensions
      id: build-image
      run: |
        cd docker/cuda-tf

        if [[ ${{ github.ref }} == refs/tags* ]]; then
          export LABEL=$(echo ${{ github.ref }} | cut -d / -f 3)
        else
          export LABEL=$(echo ${{ github.sha }} | cut -c 1-7)
        fi

        docker build . \
          --build-arg BASE_IMAGE="$DOCKER_NAME-cuda:${{ matrix.CUDA_VERSION }}-$LABEL" \
          --build-arg TF_PACKAGE_VERSION="${{ matrix.TF_VERSION }}" \
          --tag $DOCKER_NAME-cuda-tf:${{ matrix.CUDA_VERSION }}-tf-${{ matrix.TF_VERSION }}-$LABEL
        echo "IMAGE_NAME=$DOCKER_NAME-cuda-tf:${{ matrix.CUDA_VERSION }}-tf-${{ matrix.TF_VERSION }}-$LABEL" >> $GITHUB_OUTPUT
        
    - name: Image Acceptance Tests
      uses: cypress-io/github-action@v4
      env:
        TEST_IMAGE_NAME: ${{ steps.build-image.outputs.IMAGE_NAME }}
        TEST_USER_NAME: jovyan
        TEST_SPEC: jupyterlab.cy.ts
      with:
        working-directory: tests
        command: npx mocha -r ts-node/register index.ts
    - name: Push to docker
      run: |
        docker push ${{ steps.build-image.outputs.IMAGE_NAME }}

  build-py-ext:
    needs: build-py
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        EXTENSIONS:
          - vnc

    steps:
    - name: Docker Login
      uses: Azure/docker-login@v1
      with:
        username: ${{ secrets.RENKU_DOCKER_USERNAME }}
        password: ${{ secrets.RENKU_DOCKER_PASSWORD }}

    - uses: actions/checkout@v3
    - name: Build renku project python-based docker image extensions
      run: |
        if [[ ${{ github.ref }} == refs/tags* ]]; then
          export LABEL=$(echo ${{ github.ref }} | cut -d / -f 3)
        else
          export LABEL=$(echo ${{ github.sha }} | cut -c 1-7)
        fi

        # needed by the makefile
        export DOCKER_PREFIX="renku/renkulab"    
        export DOCKER_LABEL="${LABEL}"
        # this is required by the makefile
        export GIT_MASTER_HEAD_SHA=$(git rev-parse --short=7 --verify HEAD)
        make vnc 
        docker push $DOCKER_NAME-$EXTENSION:$LABEL
      env:
        EXTENSION: ${{ matrix.EXTENSIONS }}

  build-vnc-ext:
    needs: build-py-ext
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        VNC-EXTENSIONS:
          - matlab
          - qgis

    steps:
    - name: Docker Login
      uses: Azure/docker-login@v1
      with:
        username: ${{ secrets.RENKU_DOCKER_USERNAME }}
        password: ${{ secrets.RENKU_DOCKER_PASSWORD }}

    - uses: actions/checkout@v3
    - name: Build renku project python-based docker image extensions
      run: |
        if [[ ${{ github.ref }} == refs/tags* ]]; then
          export LABEL=$(echo ${{ github.ref }} | cut -d / -f 3)
        else
          export LABEL=$(echo ${{ github.sha }} | cut -c 1-7)
        fi

        # needed by the makefile
        export DOCKER_PREFIX="renku/renkulab"    
        export DOCKER_LABEL="${LABEL}"
        # this is required by the makefile
        export GIT_MASTER_HEAD_SHA=$(git rev-parse --short=7 --verify HEAD)
        # the mainfile contains targets for each of these extensions
        make vnc-$EXTENSION
        docker push $DOCKER_NAME-$EXTENSION:$LABEL
      env:
        EXTENSION: ${{ matrix.VNC-EXTENSIONS }}
        DOCKER_NAME: "renku/renkulab"

  build-py-batch:
    needs: build-py
    runs-on: ubuntu-latest

    steps:
    - name: Docker Login
      uses: Azure/docker-login@v1
      with:
        username: ${{ secrets.RENKU_DOCKER_USERNAME }}
        password: ${{ secrets.RENKU_DOCKER_PASSWORD }}

    - uses: actions/checkout@v3
    - name: Build renku project python-based docker image for batch execution
      run: |
        if [[ ${{ github.ref }} == refs/tags* ]]; then
          export LABEL=$(echo ${{ github.ref }} | cut -d / -f 3)
        else
          export LABEL=$(echo ${{ github.sha }} | cut -c 1-7)
        fi

        # needed by the makefile
        export DOCKER_PREFIX="renku/renkulab"    
        export DOCKER_LABEL="$LABEL"
        # this is required by the makefile
        export GIT_MASTER_HEAD_SHA=$(git rev-parse --short=7 --verify HEAD)
        export RENKU_BASE="$DOCKER_NAME-py:3.9-$LABEL"
        export BASE_IMAGE="python:3.9-slim-buster" 
        make batch
        echo "IMAGE_NAME=$DOCKER_NAME-batch:$DOCKER_LABEL" >> $GITHUB_OUTPUT
      env:
        DOCKER_NAME: "renku/renkulab"

  build-julia-ext:
    needs: build-py
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        JULIAVERSIONS:
          - 1.7.1

    steps:
    - name: Docker Login
      uses: Azure/docker-login@v1
      with:
        username: ${{ secrets.RENKU_DOCKER_USERNAME }}
        password: ${{ secrets.RENKU_DOCKER_PASSWORD }}

    - uses: actions/checkout@v3
    - name: Build renku project julia docker image extensions
      id: build-image
      run: |
        if [[ ${{ github.ref }} == refs/tags* ]]; then
          export LABEL=$(echo ${{ github.ref }} | cut -d / -f 3)
        else
          export LABEL=$(echo ${{ github.sha }} | cut -c 1-7)
        fi

        # needed by the makefile
        export DOCKER_PREFIX="renku/renkulab"    
        export DOCKER_LABEL="${{ matrix.JULIAVERSIONS }}-$LABEL"
        # this is required by the makefile
        export GIT_MASTER_HEAD_SHA=$(git rev-parse --short=7 --verify HEAD)
        export BASE_IMAGE="$DOCKER_NAME-py:3.9-$LABEL"
        make julia
        echo "IMAGE_NAME=$DOCKER_NAME-julia:$DOCKER_LABEL" >> $GITHUB_OUTPUT
        
    - name: Image Acceptance Tests
      uses: cypress-io/github-action@v4
      env:
        TEST_IMAGE_NAME: ${{ steps.build-image.outputs.IMAGE_NAME }}
        TEST_USER_NAME: jovyan
        TEST_SPEC: jupyterlab.cy.ts
      with:
        working-directory: tests
        command: npx mocha -r ts-node/register index.ts
    - name: Push to docker
      run: |
        docker push ${{ steps.build-image.outputs.IMAGE_NAME }}

  build-r-ubuntu:
    needs: build-py
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        include:
          - RVERSION: 4.1.0
            RSTUDIO_VERSION: 2022.02.3-492
          - RVERSION: 4.1.1
            RSTUDIO_VERSION: 2022.02.3-492
          - RVERSION: 4.1.2
            RSTUDIO_VERSION: 2022.02.3-492
          - RVERSION: 4.2.0
            RSTUDIO_VERSION: 2022.02.3-492
          - RVERSION: devel
            RSTUDIO_VERSION: 2022.02.3-492
    steps:
    - name: Docker Login
      uses: Azure/docker-login@v1
      with:
        username: ${{ secrets.RENKU_DOCKER_USERNAME }}
        password: ${{ secrets.RENKU_DOCKER_PASSWORD }}

    - uses: actions/checkout@v3
    - name: Build renku project rocker docker images
      id: build-image
      run: |
        if [[ ${{ github.ref }} == refs/tags* ]]; then
          export LABEL=$(echo ${{ github.ref }} | cut -d / -f 3)
        else
          export LABEL=$(echo ${{ github.sha }} | cut -c 1-7)
        fi

        # needed by the makefile
        export DOCKER_PREFIX="renku/renkulab"    
        export DOCKER_LABEL="${{ matrix.RVERSION }}-$LABEL"
        # this is required by the makefile
        export GIT_MASTER_HEAD_SHA=$(git rev-parse --short=7 --verify HEAD)
        export RENKU_BASE="$DOCKER_NAME-py:3.9-$LABEL"
        export BASE_IMAGE="rocker/verse:${{ matrix.RVERSION }}" 
        export RSTUDIO_VERSION_OVERRIDE="${{ matrix.RSTUDIO_VERSION }}"
        make r
        echo "IMAGE_NAME=$DOCKER_PREFIX-r:$DOCKER_LABEL" >> $GITHUB_OUTPUT

    - name: Image Acceptance Tests
      uses: cypress-io/github-action@v4
      env:
        TEST_IMAGE_NAME: ${{ steps.build-image.outputs.IMAGE_NAME }}
        TEST_ENV: rstudio
        TEST_USER_NAME: rstudio
        TEST_SPEC: rstudio.cy.ts
      with:
        working-directory: tests
        command: npx mocha -r ts-node/register index.ts

    - name: Push to docker
      run: |
        docker push ${{ steps.build-image.outputs.IMAGE_NAME }}

        # on master push latest image
        if [ "$REF" == "refs/heads/master" ] && [ "${{ matrix.RVERSION }}" == "4.2.0" ]
        then
          docker tag ${{ steps.build-image.outputs.IMAGE_NAME }} $DOCKER_NAME-r:latest
          docker push $DOCKER_NAME-r:latest
        fi

  build-bioc:
    needs: build-py
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        RELEASE:
          - RELEASE_3_14
          - RELEASE_3_15
          - devel
    steps:
    - name: Docker Login
      uses: Azure/docker-login@v1
      with:
        username: ${{ secrets.RENKU_DOCKER_USERNAME }}
        password: ${{ secrets.RENKU_DOCKER_PASSWORD }}

    - uses: actions/checkout@v3
    - name: Build renku project bioconductor docker images
      run: |
        if [[ ${{ github.ref }} == refs/tags* ]]; then
          export LABEL=$(echo ${{ github.ref }} | cut -d / -f 3)
        else
          export LABEL=$(echo ${{ github.sha }} | cut -c 1-7)
        fi

        # needed by the makefile
        export DOCKER_PREFIX="renku/renkulab"    
        export DOCKER_LABEL="${{ matrix.RELEASE }}-$LABEL"
        # this is required by the makefile
        export GIT_MASTER_HEAD_SHA=$(git rev-parse --short=7 --verify HEAD)
        export RENKU_BASE="$DOCKER_PREFIX-py:3.9-$LABEL"
        export BASE_IMAGE="bioconductor/bioconductor_docker:${{ matrix.RELEASE }}"
        make bioc
        docker push $DOCKER_PREFIX-bioc:$DOCKER_LABEL

        # on master push latest image
        if [ "$REF" == "refs/heads/master" ] && [ "${{ matrix.RELEASE }}" == "devel" ]
        then
          docker tag $DOCKER_NAME-bioc:$DOCKER_TAG $DOCKER_NAME-bioc:latest
          docker push $DOCKER_NAME-bioc:latest
        fi

